# Generated by Django 3.1.3 on 2020-12-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_curso_turno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='turno',
        ),
        migrations.AlterField(
            model_name='curso',
            name='inscriptos',
            field=models.IntegerField(verbose_name='Inscriptos'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=128, verbose_name='Nombre'),
        ),
    ]
