# Generated by Django 3.1.3 on 2020-12-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201213_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='turno',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Mañana'), (3, 'Noche'), (2, 'Tarde')], default=1, verbose_name='Turno'),
            preserve_default=False,
        ),
    ]
