# Generated by Django 3.1.3 on 2020-12-13 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201213_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='turno',
        ),
    ]
